START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260105105709_AddGuildEntities') THEN
    CREATE TABLE "Guilds" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "GuildId" text NOT NULL,
        "GuildName" text NOT NULL,
        "LastUpdated" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Guilds" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260105105709_AddGuildEntities') THEN
    CREATE TABLE "GuildMembers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "GuildId" integer NOT NULL,
        "PlayerId" integer NOT NULL,
        "Rank" text NOT NULL,
        "JoinedDate" timestamp with time zone,
        "LastUpdated" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_GuildMembers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_GuildMembers_Guilds_GuildId" FOREIGN KEY ("GuildId") REFERENCES "Guilds" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_GuildMembers_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Players" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260105105709_AddGuildEntities') THEN
    CREATE UNIQUE INDEX "IX_GuildMembers_GuildId_PlayerId" ON "GuildMembers" ("GuildId", "PlayerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260105105709_AddGuildEntities') THEN
    CREATE INDEX "IX_GuildMembers_PlayerId" ON "GuildMembers" ("PlayerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260105105709_AddGuildEntities') THEN
    CREATE UNIQUE INDEX "IX_Guilds_GuildId" ON "Guilds" ("GuildId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260105105709_AddGuildEntities') THEN
    CREATE INDEX "IX_Guilds_GuildName" ON "Guilds" ("GuildName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260105105709_AddGuildEntities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260105105709_AddGuildEntities', '9.0.0');
    END IF;
END $EF$;
COMMIT;

