using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using NibelungLog.Data;
using NibelungLog.GuildWorker.Interfaces;
using NibelungLog.GuildWorker.Services;
using NibelungLog.Interfaces;
using NibelungLog.Services;
using NibelungLog.Types.Dto;

var serviceCollection = new ServiceCollection();

serviceCollection.AddLogging(builder => builder.AddConsole());

var postgresConnectionString = Environment.GetEnvironmentVariable("POSTGRES_CONNECTION_STRING") 
    ?? "Host=localhost;Port=5432;Database=nibelunglog;Username=postgres;Password=4444";

serviceCollection.AddDbContext<ApplicationDbContext>(options =>
    options.UseNpgsql(postgresConnectionString));

var httpClientHandler = new HttpClientHandler
{
    CookieContainer = new CookieContainer(),
    UseCookies = true
};

var httpClient = new HttpClient(httpClientHandler)
{
    BaseAddress = new Uri("https://cp.wowcircle.net")
};

httpClient.DefaultRequestHeaders.Add("Accept", "application/json");
httpClient.DefaultRequestHeaders.Add("Accept-Language", "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6");
httpClient.DefaultRequestHeaders.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36");

serviceCollection.AddSingleton(httpClient);
serviceCollection.AddTransient<IWowCircleAuthService, WowCircleAuthService>();
serviceCollection.AddTransient<IGuildParserService, GuildParserService>();
serviceCollection.AddTransient<IGuildDataService, GuildDataService>();

var serviceProvider = serviceCollection.BuildServiceProvider();

var authService = serviceProvider.GetRequiredService<IWowCircleAuthService>();
var guildParserService = serviceProvider.GetRequiredService<IGuildParserService>();
var guildDataService = serviceProvider.GetRequiredService<IGuildDataService>();

const string guildName = "Сироты из Наксрамаса";
const int serverId = 5;

var loggerFactory = serviceProvider.GetRequiredService<ILoggerFactory>();
var logger = loggerFactory.CreateLogger<Program>();

logger.LogInformation("Starting guild parser for: {GuildName} on server {ServerId}", guildName, serverId);

var loginResult = await authService.LoginAsync("Mimichelik", "gepoze96", serverId);

if (!loginResult.IsAuth)
{
    logger.LogError("Failed to login to WowCircle");
    return;
}

logger.LogInformation("Login successful: Account {AccountName}, Realm {Realm}", loginResult.Name, loginResult.Realm);

using var scope = serviceProvider.CreateScope();
var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
await dbContext.Database.EnsureCreatedAsync();

var createTableSql = @"
    CREATE TABLE IF NOT EXISTS ""GuildMembers"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""GuildId"" integer NOT NULL,
        ""PlayerId"" integer NOT NULL,
        ""Rank"" text NOT NULL,
        ""JoinedDate"" timestamp with time zone NULL,
        ""LastUpdated"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_GuildMembers"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_GuildMembers_Guilds_GuildId"" FOREIGN KEY (""GuildId"") REFERENCES ""Guilds"" (""Id"") ON DELETE CASCADE,
        CONSTRAINT ""FK_GuildMembers_Players_PlayerId"" FOREIGN KEY (""PlayerId"") REFERENCES ""Players"" (""Id"") ON DELETE CASCADE
    );

    CREATE UNIQUE INDEX IF NOT EXISTS ""IX_GuildMembers_GuildId_PlayerId"" ON ""GuildMembers"" (""GuildId"", ""PlayerId"");
    CREATE INDEX IF NOT EXISTS ""IX_GuildMembers_PlayerId"" ON ""GuildMembers"" (""PlayerId"");";

await dbContext.Database.ExecuteSqlRawAsync(createTableSql);

const string guildId = "23";

logger.LogInformation("Fetching guild members for guildId: {GuildId}", guildId);

var members = await guildParserService.GetGuildMembersAsync(guildId, serverId);

var guildInfo = new GuildInfoRecord
{
    GuildId = guildId,
    GuildName = guildName
};

logger.LogInformation("Found {Count} members in guild", members.Count);

await guildDataService.SaveGuildDataAsync(guildInfo, members);

logger.LogInformation("Guild data saved successfully");

