// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NibelungLog.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NibelungLog.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260109131812_AddObsidianSanctumRaidType")]
    partial class AddObsidianSanctumRaidType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NibelungLog.Entities.CharacterSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CharacterClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClass", "Spec")
                        .IsUnique();

                    b.ToTable("CharacterSpecs");
                });

            modelBuilder.Entity("NibelungLog.Entities.Encounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AverageGearScore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DamageDealers")
                        .HasColumnType("integer");

                    b.Property<string>("EncounterEntry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncounterName")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Healers")
                        .HasColumnType("integer");

                    b.Property<int>("RaidId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<int>("Tanks")
                        .HasColumnType("integer");

                    b.Property<long>("TotalDamage")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalHealing")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RaidId", "EncounterEntry", "StartTime");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("NibelungLog.Entities.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.HasIndex("GuildName");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("NibelungLog.Entities.GuildMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GuildId", "PlayerId")
                        .IsUnique();

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("NibelungLog.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CharacterClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CharacterGender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CharacterGuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CharacterLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CharacterRace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterGuid")
                        .IsUnique();

                    b.HasIndex("CharacterName");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NibelungLog.Entities.PlayerEncounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AbsorbProvided")
                        .HasColumnType("bigint");

                    b.Property<int>("CharacterSpecId")
                        .HasColumnType("integer");

                    b.Property<long>("DamageDone")
                        .HasColumnType("bigint");

                    b.Property<double>("Dps")
                        .HasColumnType("double precision");

                    b.Property<int>("EncounterId")
                        .HasColumnType("integer");

                    b.Property<long>("HealingDone")
                        .HasColumnType("bigint");

                    b.Property<string>("MaxAverageGearScore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaxGearScore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSpecId");

                    b.HasIndex("EncounterId");

                    b.HasIndex("PlayerId", "EncounterId")
                        .IsUnique();

                    b.ToTable("PlayerEncounters");
                });

            modelBuilder.Entity("NibelungLog.Entities.Raid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AverageGearScore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompletedBosses")
                        .HasColumnType("integer");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeaderGuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeaderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaxGearScore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RaidId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RaidTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalBosses")
                        .HasColumnType("integer");

                    b.Property<long>("TotalDamage")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalHealing")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalTime")
                        .HasColumnType("bigint");

                    b.Property<int>("Wipes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaidId")
                        .IsUnique();

                    b.HasIndex("RaidTypeId");

                    b.HasIndex("StartTime");

                    b.ToTable("Raids");
                });

            modelBuilder.Entity("NibelungLog.Entities.RaidType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstanceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Map", "Difficulty", "InstanceType")
                        .IsUnique();

                    b.ToTable("RaidTypes");
                });

            modelBuilder.Entity("NibelungLog.Entities.Encounter", b =>
                {
                    b.HasOne("NibelungLog.Entities.Raid", "Raid")
                        .WithMany("Encounters")
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raid");
                });

            modelBuilder.Entity("NibelungLog.Entities.GuildMember", b =>
                {
                    b.HasOne("NibelungLog.Entities.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NibelungLog.Entities.Player", "Player")
                        .WithMany("GuildMemberships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NibelungLog.Entities.PlayerEncounter", b =>
                {
                    b.HasOne("NibelungLog.Entities.CharacterSpec", "CharacterSpec")
                        .WithMany("PlayerEncounters")
                        .HasForeignKey("CharacterSpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NibelungLog.Entities.Encounter", "Encounter")
                        .WithMany("PlayerEncounters")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NibelungLog.Entities.Player", "Player")
                        .WithMany("PlayerEncounters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterSpec");

                    b.Navigation("Encounter");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NibelungLog.Entities.Raid", b =>
                {
                    b.HasOne("NibelungLog.Entities.RaidType", "RaidType")
                        .WithMany("Raids")
                        .HasForeignKey("RaidTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaidType");
                });

            modelBuilder.Entity("NibelungLog.Entities.CharacterSpec", b =>
                {
                    b.Navigation("PlayerEncounters");
                });

            modelBuilder.Entity("NibelungLog.Entities.Encounter", b =>
                {
                    b.Navigation("PlayerEncounters");
                });

            modelBuilder.Entity("NibelungLog.Entities.Guild", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("NibelungLog.Entities.Player", b =>
                {
                    b.Navigation("GuildMemberships");

                    b.Navigation("PlayerEncounters");
                });

            modelBuilder.Entity("NibelungLog.Entities.Raid", b =>
                {
                    b.Navigation("Encounters");
                });

            modelBuilder.Entity("NibelungLog.Entities.RaidType", b =>
                {
                    b.Navigation("Raids");
                });
#pragma warning restore 612, 618
        }
    }
}
